### PR TITLE
Fixed #112 by adding check for disabled

### LINKED ISSUE #112: Site-update can't handle string 'disabled' as value for details that should be ignored
The Drupal module does not send an empty array, but rather the string value 'disabled' if Third Party Libraries aren't included in the data set.

This causes SiteDocument::setLibraries() to foreach iterate over the string 'disabled' and makes site-update fail with 'Bad request'.

I noticed the Drupal module sets the value 'disabled' for all excluded types of data, which means this error may affect other parts of the Warden server site-update route as well. You can verify this in WardenManager.php from line 143.

Steps to reproduce:

1. Setup a Drupal site with the warden module and configure it.
2. Make sure the warden_match_library setting is FALSE (the default) on your Drupal site.
3. Run a site update against your Warden server from the Drupal site using drush warden-update
4. You should see a Bad request error.

### PR DESCRIPTION
**Pull request by jcalais**

### CODE REVIEW

File: src/Deeson/WardenThirdPartyLibraryBundle/Managers/ThirdPartyLibraryManager.php [hunk 1]
```diff
@@ -80,7 +80,7 @@ public function onWardenSiteUpdate(SiteUpdateEvent $event) {
     $data = $event->getData();
     $site = $event->getSite();
     $libraryData = array();
-    if (isset($data->library)) {
+    if (isset($data->library)  && $data->library !== 'disabled') {
```
Comment (mikeddeeson) [inline src/Deeson/WardenThirdPartyLibraryBundle/Managers/ThirdPartyLibraryManager.php]: I think I would change this to use to check if $data->library was an array or not rather than checking against a defined string

Comment (jcalais) [inline src/Deeson/WardenThirdPartyLibraryBundle/Managers/ThirdPartyLibraryManager.php]: Ok! I'll push the changes. I wasn't sure if it was something that you had agreed upon, since the Drupal module appears to push 'disabled' all over the place when features are disabled. Checking for an array seems like a good solution.
